version: '2'
services:
  #backend
  backend:
    image: "backend-${ENVIRONMENT}-${CURRENT_BRANCH}-${COMMIT_HASH}"
    container_name: "backend-${ENVIRONMENT}"
    environment:
      - "DJANGO_SETTINGS_MODULE=backend.settings"
      - "RABBIT_IP=${RABBIT_IP}"
      - "RABBIT_PORT=${RABBIT_PORT}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_IP=${POSTGRES_IP}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}"
      - "SENDGRID_API_KEY=${SENDGRID_API_KEY}"
    ports:
      - "${BACKEND_IP}:${BACKEND_HTTP_PORT}:80"
    env_file: .env
    volumes:
      - medias:/home/ec2-user/efs
  # frontend
  frontend:
    image: "frontend-${ENVIRONMENT}"
    container_name: "frontend-${ENVIRONMENT}"
    ports:
      - "${NGINX_IP}:${NGINX_PORT}:80"
        
volumes:
  medias: